# Verion of docker-compose we want to use 
version: "3"

services:
  app:
    build:
      context: .
    # map port on local machine to port on docker image

    ports:
      - "8000:8000"
      
    volumes:
      - ./proj:/proj
    command: >
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"