# Verion of docker-compose we want to use 
version: "3"

services:
  proj:
    build:
      context: .
  #     map port on local machine to port on docker image

    ports:
      - "8000:8000"
      
    volumes:
      - ./proj:/proj
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=proj
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=proj
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
